### PR TITLE
added Zeta Uploader and link for gluPaste and resolve conflict

### PR DESCRIPTION
**Pull request by narendra36**

### CODE REVIEW

**Comment by narendra36** [comment]
plz review my pull request

**Comment by Akarshit** [comment]
@narendra36 Thanks for the contribution, though I feel that this list is more about what is useful to a student in a college rather than promoting softwares of NITH. I like gluPaste but am pretty sure that better alternatives for that exists and this list should only contain the best.

**Comment by narendra36** [comment]
Sir I have added zeta uploader which is useful to send large data without any login/signup for student of college and I did not add gluPaste It's already added. I just added link to gluPaste like other softwares.

**Comment by Akarshit** [comment]
@narendra36 First of all no need for "Sir", just use the nicks. 
I somehow overlooked that. Can you please remove the gluPaste and push that change to this PR again?
Also I would be very grateful if you can change the description of zeta-uploader to something that is easier to understand for beginners.
Also this has conflicts, can you fix that too.

**Comment by narendra36** [comment]
Ok

**Pull request closed without merging**
